### PR TITLE
Feature/Github Actions Add Build and publish pipeline

### PR DESCRIPTION
**Pull request by neiesc**
#3
Peding: https://github.com/L33T-KR3W/push-dir/issues/31

### CODE REVIEW

**Comment by mandaputtra** [comment]
Is there a way?

**Comment by neiesc** [comment]
I didn't try much, maybe look for another one

**Comment by neiesc** [comment]
@mandaputtra I didn't try much, maybe look for another one

**Comment by neiesc** [comment]
@mandaputtra I'm try ue https://github.com/marketplace/actions/deploy-to-github-pages

**Pull request merged**
